os:
  - linux

language: cpp

env:
  - GTEST_DIR=.

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - libgtest-dev

script:
  - cd /usr/src/gtest
  - sudo cmake .
  - sudo make
  - sudo mv libg* /usr/lib/
  - cd -
  - make lib main gtest
  - ./gobl_gtest.tsk
  
after_success:
  - make clean
